pipeline{
 environment{
   uname = "balucc/estore"
   passwd = "dockerhub"
   dockerImage = ''
}
agent{
    label 'myslave'
}
 stages{
  stage('git checkout'){
   steps{
     git 'https://github.com/balucc/eStore.git'
     }
    }
  stage('compile'){
   steps{
     withMaven(maven:'mymaven'){
    sh 'mvn compile'
   }
  }
 }
  stage('packaging'){
   steps{
    withMaven(maven:'mymaven'){
    sh 'mvn package'
    }
   }
  }
stage('DockerBuild'){
    steps{
      script{
        dockerImage = docker.build uname + ":$BUILD_NUMBER"
}
}}
stage('Docker image Push'){
  steps{
    script {
      docker.withRegistry('',passwd) {
         dockerImage.push()
          }
         }     
        }      
       }
stage('DockerRun'){
  steps{
      sh "docker run -itd -p 8085:8080 $uname:$BUILD_NUMBER"
    }
   }
  }
 }
      
